## SLURM PROLOG ###############################################################
##    Job ID : 11502159
##  Job Name : run_mult2
##  Nodelist : node1834
##      CPUs : 40
##   Mem/CPU : 2800 MB
## Directory : /oscar/home/jnickla1/fair-calibrate
##   Job Started : Fri May 16 08:52:23 PM EDT 2025
###############################################################################
>>> Constraining with cutoff year = 1930
0
1
2
3
####  • constraining/04_dump-calibration.py####
0
Dumping output...
4
####  • constraining/05_constrained-ssp-projections.py####
25
Running SSP scenarios...
Traceback (most recent call last):
  File "/oscar/home/jnickla1/fair-calibrate/input/fair-2.1.3/v1.4/all-2022_hadcrut5_current/constraining/./05_constrained-ssp-projections.py", line 58, in <module>
    df_methane = pd.read_csv(
                 ^^^^^^^^^^^^
  File "/users/jnickla1/.conda/envs/fair-calibrate/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/jnickla1/.conda/envs/fair-calibrate/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/jnickla1/.conda/envs/fair-calibrate/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/jnickla1/.conda/envs/fair-calibrate/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/users/jnickla1/.conda/envs/fair-calibrate/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../../../../output/fair-2.1.3/v1.4/all-2022_hadcrut5_currentcut1930/calibrations/CH4_lifetime.csv'
ERROR in constraining/05_constrained-ssp-projections.py for cutoff 1930
